name: lystui
description: Simple app to manage notes in categories

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^4.0.2
  flutter_secure_storage: ^3.3.1+1
  flutter_dotenv: ^2.1.0
  http: ^0.12.0+4
  cupertino_icons: ^0.1.2
  tinycolor: ^1.0.2
  shimmer: ^1.1.1
  animations: ^1.0.0+5
  i18n_extension: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
    - .envDev

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
